version: '3'

services:


  greenmail:

    image: greenmail/standalone:latest

    environment:

      - JAVA_OPTS=-Dgreenmail.verbose

    ports:

      - 3025:3025 # SMTP

      - 3110:3110 # POP3

      - 3143:3143 # IMAP

      - 3465:3465 # SMTPS

      - 3993:3993 # IMAPS

      - 3995:3995 # POP3S

      - 8081:8080 # API



  maildev:

    image: maildev/maildev:latest

    depends_on:

      - greenmail

    ports:

      - 25:1025
      - 1080:1080

    environment:

      - MAILDEV_DEFAULT_HOST=greenmail  # IMAP server - tls:// prefix for STARTTLS, ssl:// for SSL/TLS

      - MAILDEV_DEFAULT_PORT=3143       # IMAP port

      - MAILDEV_SMTP_SERVER=greenmail   # SMTP server - tls:// prefix for STARTTLS, ssl:// for SSL/TLS

      - MAILDEV_SMTP_PORT=1025          # SMTP port

